-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Dphones.Object exposing (..)


type Mixen
    = Mixen


type Mixen_aggregate
    = Mixen_aggregate


type Mixen_aggregate_fields
    = Mixen_aggregate_fields


type Mixen_avg_fields
    = Mixen_avg_fields


type Mixen_max_fields
    = Mixen_max_fields


type Mixen_min_fields
    = Mixen_min_fields


type Mixen_mutation_response
    = Mixen_mutation_response


type Mixen_stddev_fields
    = Mixen_stddev_fields


type Mixen_stddev_pop_fields
    = Mixen_stddev_pop_fields


type Mixen_stddev_samp_fields
    = Mixen_stddev_samp_fields


type Mixen_sum_fields
    = Mixen_sum_fields


type Mixen_var_pop_fields
    = Mixen_var_pop_fields


type Mixen_var_samp_fields
    = Mixen_var_samp_fields


type Mixen_variance_fields
    = Mixen_variance_fields


type Set
    = Set


type Set_aggregate
    = Set_aggregate


type Set_aggregate_fields
    = Set_aggregate_fields


type Set_max_fields
    = Set_max_fields


type Set_min_fields
    = Set_min_fields


type Set_mutation_response
    = Set_mutation_response
