-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Dphones.ScalarCodecs exposing (..)

import Dphones.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Date =
    Dphones.Scalar.Date


codecs : Dphones.Scalar.Codecs Date
codecs =
    Dphones.Scalar.defineCodecs
        { codecDate = defaultCodecs.codecDate
        }
