-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Dphones.Enum.Set_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "set"

  - Set\_pkey - unique or primary key constraint on columns "tag"

-}
type Set_constraint
    = Set_pkey


list : List Set_constraint
list =
    [ Set_pkey ]


decoder : Decoder Set_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "set_pkey" ->
                        Decode.succeed Set_pkey

                    _ ->
                        Decode.fail ("Invalid Set_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Set_constraint -> String
toString enum____ =
    case enum____ of
        Set_pkey ->
            "set_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Set_constraint
fromString enumString____ =
    case enumString____ of
        "set_pkey" ->
            Just Set_pkey

        _ ->
            Nothing
