-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Dphones.Enum.Set_update_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| update columns of table "set"

  - Date - column name
  - Tag - column name
  - Title - column name

-}
type Set_update_column
    = Date
    | Tag
    | Title


list : List Set_update_column
list =
    [ Date, Tag, Title ]


decoder : Decoder Set_update_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "date" ->
                        Decode.succeed Date

                    "tag" ->
                        Decode.succeed Tag

                    "title" ->
                        Decode.succeed Title

                    _ ->
                        Decode.fail ("Invalid Set_update_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Set_update_column -> String
toString enum____ =
    case enum____ of
        Date ->
            "date"

        Tag ->
            "tag"

        Title ->
            "title"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Set_update_column
fromString enumString____ =
    case enumString____ of
        "date" ->
            Just Date

        "tag" ->
            Just Tag

        "title" ->
            Just Title

        _ ->
            Nothing
